---
---
sudo: false
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.1
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 4.10.0" STRICT_VARIABLES=yes
